// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhSAa1SZDinh1KtNYeB2sB0DBbCPVrXA',
    appId: '1:222187166807:web:8648d4dd3a8ba82ed81712',
    messagingSenderId: '222187166807',
    projectId: 'mynotes-kojo-api',
    authDomain: 'mynotes-kojo-api.firebaseapp.com',
    storageBucket: 'mynotes-kojo-api.appspot.com',
    measurementId: 'G-NDR7L85G78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPh1Rw5rSxz-jVnjhi19wyqX_kpjfGes',
    appId: '1:222187166807:android:6e7de83f4613608ed81712',
    messagingSenderId: '222187166807',
    projectId: 'mynotes-kojo-api',
    storageBucket: 'mynotes-kojo-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh-nPwxVA7WkLAZw8mCwNufxWxJ0M5VWA',
    appId: '1:222187166807:ios:01226e9754f971aed81712',
    messagingSenderId: '222187166807',
    projectId: 'mynotes-kojo-api',
    storageBucket: 'mynotes-kojo-api.appspot.com',
    iosClientId: '222187166807-8cbibifss0frp0iuhusnvk87g27anofo.apps.googleusercontent.com',
    iosBundleId: 'gh.eldakk.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh-nPwxVA7WkLAZw8mCwNufxWxJ0M5VWA',
    appId: '1:222187166807:ios:01226e9754f971aed81712',
    messagingSenderId: '222187166807',
    projectId: 'mynotes-kojo-api',
    storageBucket: 'mynotes-kojo-api.appspot.com',
    iosClientId: '222187166807-8cbibifss0frp0iuhusnvk87g27anofo.apps.googleusercontent.com',
    iosBundleId: 'gh.eldakk.mynotes',
  );
}
